name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        working-directory: ./backend  # Set the working directory to 'backend'
        run: npm install

      - name: Run SonarQube Scanner
        working-directory: ./backend  # Ensure the scanner runs in 'backend'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          npm install sonarqube-scanner --save-dev
          npm run sonar \
            -Dsonar.projectKey=Celesca_hack2gather \
            -Dsonar.sources=./src \
            -Dsonar.exclusions=**/node_modules/** \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
